data:
  root: "MedPix-2-0"
  batch_size: 16
  num_workers: 4

teacher:
  vision: "vit-large"
  text: "bio-clinical-bert"
  fusion_layers: 2

student:
  vision: "deit-base"
  text: "distilbert"
  fusion_layers: 1

training:
  teacher_epochs: 1
  student_epochs: 1
  teacher_lr: 1e-5
  student_lr: 3e-4
  alpha: 1.0
  beta: 100.0
  T: 2.0

logging:
  log_dir: "logs"

fusion:
  type: "simple"

loss:
#  type: "vanilla"
#  type: "combined"
#  type: "crd"
  type: "rkd"
#  type: "mmd"
  