data:
  type: "wound"
  root: "datasets/Wound-1-0"
  batch_size: 8
  num_workers: 2
  # Column names in metadata.csv
  type_column: "type"
  severity_column: "severity"
  description_column: "description"
  filepath_column: "img_path"

teacher:
  vision: "vit-base"
  text: "distilbert"
  fusion_layers: 1
  fusion_dim: 256

student:
  vision: "deit-base"
  text: "distilbert"
  fusion_layers: 1
  fusion_dim: 256

training:
  teacher_epochs: 1
  student_epochs: 1
  teacher_lr: 1e-5
  student_lr: 3e-4
  alpha: 1.0
  beta: 100.0
  T: 2.0

logging:
  log_dir: "logs/test_wound_1epoch"

fusion:
  type: "simple"

loss:
  type: "vanilla"

device: "cuda:4"
