data:
  root: "datasets/MedPix-2-0"
  batch_size: 8
  num_workers: 2
  # Task labels for metrics
  task1_label: "modality"
  task2_label: "location"

teacher:
  vision: "vit-base"
  text: "bio-clinical-bert"
  fusion_layers: 1
  fusion_dim: 256
  fusion_heads: 8
  dropout: 0.1

student:
  vision: "deit-base"
  text: "distilbert"
  fusion_layers: 1
  fusion_dim: 256
  fusion_heads: 8
  dropout: 0.1

training:
  teacher_epochs: 1
  student_epochs: 1
  teacher_lr: 1e-5
  student_lr: 3e-4
  alpha: 1.0
  beta: 100.0
  T: 2.0

logging:
  log_dir: "logs/test_1epoch"

fusion:
  type: "simple"

loss:
  type: "vanilla"

device: "cuda:4"
