data:
  type: "wound"
  root: "datasets/Wound-1-0"
  batch_size: 16
  num_workers: 4
  task1_label: "type"
  task2_label: "severity"
  type_column: "type"
  severity_column: "severity"
  description_column: "description"
  filepath_column: "img_path"

teacher:
  vision: "vit-base"
  text: "bio-clinical-bert"
  fusion_layers: 2
  fusion_dim: 384
  fusion_heads: 8
  dropout: 0.18490502670069944

student:
  vision: "deit-small"
  text: "minilm"
  fusion_layers: 2
  fusion_dim: 384
  fusion_heads: 4
  dropout: 0.2383060985066181

training:
  teacher_epochs: 3
  student_epochs: 10
  teacher_lr: 4.786827188881545e-05
  student_lr: 0.00010451580210282471
  alpha: 0.5182561547439836
  beta: 112.37763676785187
  T: 3.1921579031760037

logging:
  log_dir: "logs/ultra-edge-tuned-hp/wound-deit_small-minilm"

fusion:
  type: "cross_attention"

loss:
  type: "combined"

device: "cuda:0"
