data:
  type: "wound"
  root: "datasets/Wound-1-0"
  batch_size: 8
  num_workers: 4
  type_column: "type"
  severity_column: "severity"
  description_column: "description"
  filepath_column: "img_path"
  task1_label: "type"
  task2_label: "severity"

teacher:
  vision: "vit-base"
  text: "bio-clinical-bert"
  fusion_layers: 2
  fusion_dim: 384

student:
  vision: "deit-tiny"
  text: "distilbert"
  fusion_layers: 1
  fusion_dim: 384

training:
  teacher_epochs: 3
  student_epochs: 10
  teacher_lr: 1e-5
  student_lr: 3e-4
  alpha: 1.0
  beta: 100.0
  T: 2.0

logging:
  log_dir: "logs/ultra-edge2/wound-deit_tiny-distilbert-384"

fusion:
  type: "cross_attention"

loss:
  type: "combined"

device: "cuda:3"
